package table

import "context"

type GenerateFuncImpl func(ctx context.Context, queryContext QueryContext) ([]RowDefinition, error)

// Generate returns the rows generated by the table. The ctx argument
// should be checked for cancellation if the generation performs a
// substantial amount of work. The queryContext argument provides the
// deserialized JSON query context from osquery.
func GenerateFunc(impl GenerateFuncImpl) Option {
	return func(plugin *Plugin) {
		plugin.generate = impl
	}
}
